IA/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include


urlpatterns = [
    path('', include("usuarios.urls")),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from usuarios.views import * 
from usuarios import views

app_name = 'usuarios'

urlpatterns = [
    path('', views.index, name="home"),
    path('listarUsuarios/', UsuariosListar.as_view(), name= 'listar_usuarios'),
    path('listarVehiculos/', VehiculosListar.as_view(), name= 'listar_vehiculos'),
    path('usuario/crear', UsuariosCrear.as_view(), name= 'usuario_crear'),
    path('vehiculo/crear', VehiculosCrear.as_view(), name= 'vehiculo_crear'),
    path('usuario/modificar/<int:pk>', UsuariosModificar.as_view(), name = 'usuario_modificar'),
    path('vehiculo/modificar/<int:pk>', VehiculosModificar.as_view(), name = 'vehiculo_modificar'),
    path('usuario/eliminar/<int:pk>', UsuariosEliminar.as_view(), name='usuario_eliminar'),
    path('vehiculo/eliminar/<int:pk>', VehiculosEliminar.as_view(), name='vehiculo_eliminar'),


]

templates/base.html
<!doctype html>
{% load static %}
<html lang="es" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    {% comment %} <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css.map' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css.map' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css.map' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css.map' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css.map' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css.map' %}">


    <title>{% block title %}Reconocimiento de Placas{% endblock %}</title>
  </head>
  <nav class="navbar sticky-top navbar-light bg-light" >
    <ul class="nav">
        <div class="container-fluid">
                <h1>Reconocimiento de Placas de vehiculos y busqueda en la BD sus respectivos datos</h1>
        </div>
    </ul>
    <ul class="nav justify-content-end">
        <li class="nav-item">
            <div class="cent">
                <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                    <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
                </a>
                <span class="text-muted">© 2021 Grupo 10 &nbsp;&nbsp;&nbsp;&nbsp;</span>
            </div>
        </li>
    </ul>
</nav>
  <body class="body">
    {% block content %}
    {% endblock %}
    {% comment %} <script src="{% static 'js/bootstrap.min.js'%}" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script> {% endcomment %}
    <script src="{% static 'js/bootstrap.min.js'%}" ></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html'%}
{% block content %}
    <div class="card">
        <div class="card-body">
            <div >
                <table class="table table-striped">
                    <td>
                        <label>Datos ingresados en al BD:  &nbsp;&nbsp;&nbsp;&nbsp;</label>
                        <a class="btn btn-outline-primary" type="button" href="{% url 'usuarios:listar_usuarios'%}">Listar Usuarios</a>
                        &nbsp;&nbsp; 
                        <a class="btn btn-outline-primary" type="button" href="{% url 'usuarios:listar_vehiculos'%}">Listar Vehiculos</a> 
                        &nbsp;&nbsp; 
                        {%if  estado != None %}
                            <a class="btn btn-outline-primary" type="button" href="{% url 'usuarios:home'%}">Home</a>
                        {% endif %}
                    </td>
                </table>
            </div>
            {%if  estado == None %}
            <div text-align = "center">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-body ">
                        <div class="container">
                            <div class="input-group mb-3">
                                <div class="input-group input-group-sm mb-3">
                                    <input class="form-control" type="file" name="imageFile" accept="image/jpeg"/>
                                    <input class="btn btn-outline-secondary" type="submit" name="submit" value="Upload" />
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            {% endif %}
            {% if datos %}
            <table class="table">
                <td style="width:35%;" >
                    {%if area %}
                        <p class="fs-4">Placa detectada por el sistema es: "{{area}}"</p>
                    {%endif%}
                    <div class="container-fluid">
                        <figure class="figure">
                            <img src = "{{url}}" class="figure-img img-fluid rounded" width="100%">
                            <p class="fs-3" align="center"><p class="text-uppercase"><figcaption class="figure-caption">La imagen contiene una {{predictions}} y {{datos}}</figcaption></p></p>
                        </figure>
                    </div>
                    {%endif%}
                    {%if error %}
                        <div class="container-fluid">   
                            <p class="fs-4">{{error}}</p>
                        </div>
                    {%endif%}
                </td>
                <td>
                    {% if placa != None%}
                        <div class="container">
                            <div class="container-fluid">
                                <figure class="figure">
                                    <p class="fs-3" align="center"><p class="text-uppercase"><figcaption class="figure-caption">La imagen de la placa es:</figcaption></p></p>
                                    <img src = "{{placa}}" class="figure-img img-fluid rounded" width="200%">
                                </figure>
                            </div> 
                        </div>
                    {%endif%}
                    {%if datosVehiculo != None %}
                    <div class="card">
                        {% if mensaje %}
                            <h5 class="card-header">{{mensaje}}</h5>
                        {% endif %}
                            <div class="card-body">
                                <table class="table table-borderles">
                                    <td style="width:50%;">
                                        <div class="card-body">
                                            <div class="col-md-10 col-md-offset-2">
                                                <div class="form-group">
                                                    <p class="fw-bold">Datos del Usuario:</p>
                                                </div>
                                            </div>
                                            <div class="col-md-10 col-md-offset-2">
                                                <div class="form-group">
                                                    <label class="fw-normal"> &nbsp;&nbsp;&nbsp;&nbsp; <b>Nombres:</b></label> <label class="fw-light">{{datosUsuarioNombres}}</label>
                                                </div>
                                            </div>
                                            <div class="col-md-10 col-md-offset-2">
                                                <div class="form-group">
                                                    <label class="fw-normal"> &nbsp;&nbsp;&nbsp;&nbsp; <b>Apellidos:</b></label> <label class="fw-light">{{datosUsuarioApellidos}} </label>
                                                </div>
                                            </div>
                                            <div class="col-md-10 col-md-offset-2">
                                                <div class="form-group">
                                                    <label class="fw-normal"> &nbsp;&nbsp;&nbsp;&nbsp; <b>Direccion:</b></label> <label class="fw-light"> {{datosUsuarioDireccion}}</label> 
                                                </div>
                                            </div>
                                            <div class="col-md-10 col-md-offset-2">
                                                <div class="form-group">
                                                    <label class="fw-normal"> &nbsp;&nbsp;&nbsp;&nbsp; <b>Telefono:</b></label> <label class="fw-light"> {{datosUsuarioTelefono}}</label>
                                                </div>
                                            </div>
                                            <div class="col-md-10 col-md-offset-2">
                                                <div class="form-group">
                                                    <label class="fw-normal"> &nbsp;&nbsp;&nbsp;&nbsp; <b>Dui:</b></label> <label class="fw-light"> {{datosUsuarioDui}}</label> 
                                                </div>
                                            </div>
                                            <div class="col-md-10 col-md-offset-2">
                                                <div class="form-group">
                                                    <label class="fw-normal"> &nbsp;&nbsp;&nbsp;&nbsp; <b>Numero de Licencia:</b></label> <label class="fw-light"> {{datosUsuarioLicencia}}</label> 
                                                </div>
                                            </div>
                                        </div>                 
                                    </td>
                                    <td>
                                        <div class="card-body">
                                            <div class="col-md-10 col-md-offset-2">
                                                <div class="form-group">
                                                    <p class="fw-bold">Datos del Vehiculo:</p>
                                                </div>
                                            </div>
                                            <div class="col-md-10 col-md-offset-2">
                                                <div class="form-group">
                                                    <label class="fw-normal"> &nbsp;&nbsp;&nbsp;&nbsp; <b>Matricula:</b></label> <label class="fw-light">{{datosVehiculo}}</label>
                                                </div>
                                            </div>   
                                            <div class="col-md-10 col-md-offset-2">
                                                <div class="form-group">
                                                    <label class="fw-normal"> &nbsp;&nbsp;&nbsp;&nbsp; <b>Modelo:</b></label> <label class="fw-light">{{datosVehiculoModelo}}</label>
                                                </div>
                                            </div>  
                                            <div class="col-md-10 col-md-offset-2">
                                                <div class="form-group">
                                                    <label class="fw-normal"> &nbsp;&nbsp;&nbsp;&nbsp; <b>Color:</b></label> <label class="fw-light">{{datosVehiculoColor}}</label>
                                                </div>
                                            </div>  
                                            <div class="col-md-10 col-md-offset-2">
                                                <div class="form-group">
                                                    <label class="fw-normal"> &nbsp;&nbsp;&nbsp;&nbsp; <b>Año:</b></label> <label class="fw-light">{{datosVehiculoAnio}}</label>
                                                </div>
                                            </div>  
                                        </div>
                                    </td>
                                </table>
                            </div>
                        </div>
                    {%endif%}
                </td>
        </div>
    </div >
{% endblock %}

templates/listarUsuarios.html
{% extends 'base.html'%}
{% block content %}
<div class="container-fluid">
    <div class="card-body">
        <div class="card-body">
            <div>
                <a class="btn btn-outline-primary" href={% url 'usuarios:home'%}>Home</a>
                <a class="btn btn-outline-secondary" href={% url 'usuarios:listar_vehiculos'%}>Listar Vehiculos</a>
            </div>
            <div>
                <h1> Lista de todos los Usuarios Registrados</h1>
            </div>
            <div>
                <div>
                    <a class="btn btn-outline-primary" href="{% url 'usuarios:usuario_crear' %}">Ingresar Usuario</a>
                </div>
            </div>
            {% if object_list %}
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Nombres</th>
                            <th>Apellidos</th>
                            <th>Direccion</th>
                            <th>Telefono</th>
                            <th>Dui</th>
                            <th>Fecha Nac.</th>
                            <th>Licencia</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for usuarios in object_list %}
                        <tr>
                            <td>{{ usuarios.nombres }}</td>
                            <td>{{ usuarios.apellidos }}</td>
                            <td>{{ usuarios.direccion }}</td>
                            <td>{{ usuarios.telefono }}</td>
                            <td>{{ usuarios.dui }}</td>
                            <td>{{ usuarios.fechaNacimiento }}</td>
                            <td>{{ usuarios.licencia }}</td>
                            <td> 
                                <table>
                                    <td>
                                        <a type="button" class="btn btn-outline-success" href="{% url 'usuarios:usuario_modificar' usuarios.pk %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                        </svg></a>
                                    </td>
                                    <td>
                                        <a class="btn btn-outline-danger" type="button" class = "btn btn-primary" href="{% url 'usuarios:usuario_eliminar' usuarios.pk %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                        </svg></a>
                                    </td>
                                </table>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <li>No hay registros de Usuarios</li>
            {% endif%}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/listarVehiculos.html
{% extends 'base.html'%}
{% block content %}
<div class="container-fluid">
    <div class="card-body">
        <div class="card-body">
            <div>
                <a class="btn btn-outline-primary" href={% url 'usuarios:home'%}>Home</a>
                <a class="btn btn-outline-secondary" href={% url 'usuarios:listar_usuarios'%}>Listar Usuarios</a>
            </div>
            
            <div>
                <h1> Lista de todos los Vehiculos Registrados</h1>
            </div>
            <div>
                <div>
                    <a class="btn btn-outline-primary" href="{% url 'usuarios:vehiculo_crear' %}">Ingresar Vehiculo</a>
                </div>
            </div>
            {% if object_list %}
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Usuario</th>
                            <th>Matricula</th>
                            <th>Modelo</th>
                            <th>Color</th>
                            <th>Año</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for vehiculos in object_list %}
                        <tr>
                            <td>{{ vehiculos.usuario }}</td>
                            <td>{{ vehiculos.matricula }}</td>
                            <td>{{ vehiculos.modelo }}</td>
                            <td>{{ vehiculos.color }}</td>
                            <td>{{ vehiculos.anio }}</td>
                            <td> 
                                <table>
                                    <td>
                                        <a type="button" class="btn btn-outline-success" href="{% url 'usuarios:vehiculo_modificar' vehiculos.pk %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                        </svg></a>
                                    </td>
                                    <td>
                                        <a class="btn btn-outline-danger" type="button" class = "btn btn-primary" href="{% url 'usuarios:vehiculo_eliminar' vehiculos.pk %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                        </svg></a>
                                    </td>
                                </table>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <li>No hay registros de vehiculos</li>
            {% endif%}
    </div>
{% endblock %}